sudo: false
language: elixir
elixir:
  - 1.6.0
  - 1.7.0
  - 1.8.0
  - 1.9.0
  - 1.10.0
  - 1.11.0
otp_release:
  - 19.0
  - 20.0
  - 21.0
  - 22.0
  - 23.0
matrix:
  exclude:
    - elixir: 1.6.0
      otp_release: 21.0
    - elixir: 1.6.0
      otp_release: 22.0
    - elixir: 1.6.6
      otp_release: 22.0
    - elixir: 1.8.0
      otp_release: 19.0
    - elixir: 1.9.0
      otp_release: 19.0
    - elixir: 1.10.0
      otp_release: 19.0
    - elixir: 1.11.0
      otp_release: 19.0
